repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files

